name: Main Foodgram Workflow

on:
    push:
        branches:
            - main

jobs:
    tests:
        name: PEP8 flake8 check, ruff linting
        runs-on: ubuntu-latest

        # services:

        #     postgres:
        #         image: postgres:13.0-alpine
        #         env:
        #             POSTGRES_USER: postgres
        #             POSTGRES_PASSWORD: postgres
        #         ports:
        #             - 5432:5432

        #         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Python setup
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install -r backend/requirements.txt

            - name: Test with flake8
              run: |
                python -m flake8

            - name: Lint with ruff
              run: python -m ruff check backend/

            # - name: Install Postman CLI
            #   run: |
            #     curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

            # - name: Login to Postman CLI
            #   run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

            # - name: Run API tests
            #   run: |
            #     postman collection run "40798897-0f02157e-e43f-4516-9e16-5eadd02a07b4" --env-var "baseUrl=localhost:8001"
