name: Main Foodgram Workflow

on:
    push:
        branches:
            - main

jobs:
    tests:
        name: PEP8 flake8 check, ruff linting
        runs-on: ubuntu-latest

        # services:

        #     postgres:
        #         image: postgres:13.0-alpine
        #         env:
        #             POSTGRES_USER: postgres
        #             POSTGRES_PASSWORD: postgres
        #         ports:
        #             - 5432:5432

        #         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Python setup
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install -r backend/requirements.txt

            - name: Test with flake8
              run: python -m flake8

            - name: Lint with ruff
              run: python -m ruff check backend/

    build_and_push_to_docker_hub:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        needs: tests
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Docker 
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Push backend to Docker Hub
            uses: docker/build-push-action@v5
            with:
                context: ./backend
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
              
          - name: Push frontend to Docker Hub
            uses: docker/build-push-action@v5
            with:
                context: ./frontend
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest

    send_message:
        name: Send success message
        runs-on: ubuntu-latest
        needs: build_and_push_to_docker_hub
        steps:
            - name: Send message
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                message: Образы успешно загружены!

            # - name: Install Postman CLI
            #   run: |
            #     curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

            # - name: Login to Postman CLI
            #   run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

            # - name: Run API tests
            #   run: |
            #     postman collection run "40798897-0f02157e-e43f-4516-9e16-5eadd02a07b4" --env-var "baseUrl=localhost:8001"
